### PR TITLE
feat: add privacy level enum [SD-781]

### PR DESCRIPTION
**Pull request by ricardodcpereira**
This PR adds the privacy level enum to be used on other packages.

### CODE REVIEW

**Comment by aquemy** [comment]
My stance on the organization of this repo is to move this privacy enum to 
/synthesizers/privacy.py or /synthesizers/privacy/privacy_level.py

As it is an import for the synthesizer instance itself and needs to be available to the user, we should also export is in the /synthesizer folder:

`import ydata.core.synthesizers.PrivacyLevel`

if we don't want the user to directly import from core, we can always re-export it locally in each product (SDK, DS lib, etc).

**Comment by portellaa** [comment]
For me, the only drawback on this, is that this can increate a lot, i would probably remove this from the core and move to a standalone level so we can import it as ydata-synthesizers, or ydata-datascience-synthesizers, ... and then just import that.

I don't see this as core because as a developer, i don't use it everywhere (i actually don't need it) ... you get the idea, i guess.
But for sure i'm keen to reduce the amount of duplicated objects that we have

**Comment by aquemy** [comment]
@portellaa you mean having a subpackage just for these common object for data science? If so, I suggest `ydata-datascience-common`. It will contain mostly definition and enums, so nothing too heavy.

**Comment by ricardodcpereira** [comment]
@aquemy @portellaa the privacy level enum was moved to a new data science package. @vascoalramos will update the makefile after the PR is approved.

**Pull request merged**
